# Quizzes & Tasks

In [43]:
import numpy as np
X1 = np.random.randint(0,10,(4,2))
X2 = np.random.randint(0,10,(5,2))
X3 = np.random.randint(0,10,(6,2))
c = np.concatenate((X1,X2,X3))
c.shape


(15, 2)

In [64]:
Z = np.array(list(range(5)))
X1 = Z.reshape(1,5)
X2 = Z.reshape(5)
c = X1*X2
c.shape
c


array([[ 0,  1,  4,  9, 16]])

In [77]:
X = np.array(list(range(6)))
X = X.reshape(2,3)
print(X < 4)
print(X[X < 4])

[[ True  True  True]
 [ True False False]]
[0 1 2 3]


In [85]:
X = [[1,0,1]]
X= np.concatenate((X,X))
print(X)
print(np.all( X == 0, axis = 0))
print(np.any( X == 1, axis = 1))

[[1 0 1]
 [1 0 1]]
[False  True False]
[ True  True]


In [87]:
X = np.array(list(range(9)))
X = X.reshape(3,3)
print(X[ [2, 1, 0], [ 0, 2, 1]])
print(X[1 , [2, 0, 1]])

[6 5 1]
[5 3 4]


In [89]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])