### === Task 1 ===

1. Declare a list of 1 to 4 using range()

2. Continuing, create numpy array from this list, with dtype='float32'

3. Create an numpy array of size 3 by 5 using np.zeros

4. Create an numpy array of size 2 by 3 with filled value 1 / 3

5. Create an array of 5 equal-distanced values for 0 to 10

6. Create an array of number for 0.001, 0.01, 0.1, 1 using np.logspace

7. Create a diagonal matrix of list [1, 2, 3, 4]


8. Create a random array of size 4 by 5 all filled with random values between 0 and 1

9.  Create a random array of size 4 by 5 all filled with integer random values between 2 and 5

10.  Create a random array of size 4 by 5 all filled with float random values between 2 and 5

11. Create a random array of size 4 by 5 with mean = 5, and std = 1 following a gaussian (normal) distribution

12. Create an identity matrix of size 5 by 5

In [200]:
# 1.
a_list = list(range(1,5))
print(a_list)

[1, 2, 3, 4]


In [201]:
# 2.
import numpy as np
arr = np.array((a_list), dtype='float32')
print(arr)

[1. 2. 3. 4.]


In [202]:
# 3.
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [203]:
# 4. 
print(np.full((2, 3), 1/3))

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [204]:
# 5.
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [205]:
# 6. 
print(np.logspace(-3, 0, 4))

[0.001 0.01  0.1   1.   ]


In [206]:
# 7.
print(np.diag(np.arange(1, 5)))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [207]:
# 8.
print(np.random.random((4, 5)))

[[0.20101541 0.5299955  0.95121072 0.84546574 0.70715747]
 [0.21298611 0.52709836 0.65421519 0.44570296 0.35605395]
 [0.10877916 0.00246546 0.85002181 0.61933181 0.5308086 ]
 [0.37748379 0.72081456 0.70010514 0.87979034 0.92349877]]


In [208]:
# 9.
print(np.random.randint(12, 15, (4, 5)))

[[14 14 13 14 12]
 [14 14 13 13 14]
 [12 12 14 13 14]
 [13 14 14 14 14]]


In [209]:
# 10.
print(np.random.uniform(low=2, high=5, size=(4, 5)))

[[4.57890304 3.1748769  3.85071262 4.45905129 4.47957139]
 [3.12599522 3.00185501 3.28987085 3.56100818 4.39565442]
 [4.71061325 3.36544408 4.32663822 4.4505963  4.60695779]
 [2.85628737 2.33971759 3.85821227 4.15114568 3.01725117]]


In [210]:
# 11. 
print(np.random.normal(5, 1, (4, 5))) 
#mean = 5, and std = 1, size = (4, 5)

[[6.23860739 5.04574139 3.31819771 4.53479085 5.91695491]
 [3.87507741 3.94046298 4.92875734 5.4505734  4.39029173]
 [4.94414796 4.9378125  3.6429499  5.66451478 3.83561699]
 [5.02499402 4.10499478 3.64442569 5.20574707 4.0632621 ]]


In [211]:
# 12. Create an identity matrix of size 5 by 5
print(np.identity(5))
# OR np.eye(5) -> equivalent

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### === Task 2 ===

1. Create a numpy array of size 3 by 4 with random float values between 1 to 5

2. Continuing, print the shape of this array

3. Continuing, access the first row of the array

4. Continuing, access the first column of the array

5. Continuing, access the second row, and third column element

6. Continuing, access the first two columns

7. Continuing, access the  first and third columns using step

8. Continuing, print the whole matrix in reverse columns but not rows

9. Change the third row, fourth column element (i.e., the last element) to 999

In [212]:
# 1.
#a = np.random.uniform(1, 5, (3, 4))
a = np.random.randint(1, 5, (3, 4))
print(a)

[[4 2 4 4]
 [2 2 2 4]
 [3 3 2 3]]


In [213]:
# 2.
print(a.shape)

(3, 4)


In [214]:
# 3.
print(a[:1])

[[4 2 4 4]]


In [215]:
# 4.
print(a[:, :1])

[[4]
 [2]
 [3]]


In [216]:
# 5.
print(a[1, 2])

2


In [217]:
# 6.
print(a[:, :2])

[[4 2]
 [2 2]
 [3 3]]


In [218]:
# 7.
print(a[:, ::2])

[[4 4]
 [2 2]
 [3 2]]


In [219]:
# 8. 
print(a[:, ::-1])

[[4 4 2 4]
 [4 2 2 2]
 [3 2 3 3]]


In [220]:
# 9.
a[2,3] =999
print(a)

[[  4   2   4   4]
 [  2   2   2   4]
 [  3   3   2 999]]


### === Task 3 ===

1. Create a numpy array of size 200 by 4 with random float values between 1 to 5 and name it <code>Data</code>

2. Split the array into two numpy arrays, X and y, where the X contains the first 3 columns and y contains the last column.

3. Continuing, split the first 70% of the 200 rows of X and y and call them <code>X_train</code> and <code>y_train</code>. Similarly, populate <code>X_test</code> and <code>y_test</code> using same corresponding columns but 30\% rest of the data.

<img src="figures/02.07-numpy-Task.png" width=1000 height=1000 />

4. Print the shape of the <code>X_train</code> and <code>y_train</code>.  The first array should have shape (0.7 * 200, 3); the second array is (0.7 * 200, 1)

5. Assign m = <code>X_train.shape[0]</code>, and n = <code>X_train.shape[1]</code>, where $m$ is number of samples, and $n$ is number of features

6. Randomly select one row of <code>X_train</code> by using <code>np.random.randint</code> to select the random row and called it <code>X_i</code>.  Reshape it so that it has shape of <code>(1, n)</code>

7. Randomly select 50 contiguous rows from <code>X_train</code> by using <code>np.random.randint</code> to select a random starting row and called it <code>mini_batch_X</code>.  If the index exceeds, simply grab whatever left.

8. Write a for loop that breaks the <code>X_train</code> row-wise into 10 equal pieces without overlap, and simply print their shape

9. Create an np.zero array called <code>theta</code> with shape of <code>(n, )</code>

10. Perform a **dot product** between <code>X_train</code> and <code>theta</code> and assign this value to a variable called <code>yhat</code>
Hint: https://www.guru99.com/numpy-dot-product.html

<center><img src="figures/02.07-numpy-Task-dot-explained.png" width=500 height=500 /></center>

11. Create another variable called <code>y</code> with the same shape as <code>yhat</code>, and populate it with random values from 0 to 1.

12. Calculate the following 
    $$ \frac{\sum\limits_{i=1}^{m} (y_i - \hat{y_i})^2}{m} $$
    
    For example, if yhat = [1, 2, 3] and y = [2, 3, 4], then the calculation is
    
    $$ \frac{sum((1-2)^2 + (2-3)^2 + (3-4)^2)}{m} $$

In [221]:
# 1.
Data = np.random.uniform(1, 5, (200, 4))
print(Data.shape)

(200, 4)


In [222]:
# 2.
X = Data[:, :3]
y = Data[:, 3]
print(X.shape)
print(y.shape)

(200, 3)
(200,)


In [223]:
# 3. 
train_size = int(0.7 * Data.shape[0])
X_train = X[:train_size,:]
X_test = X[train_size:,:]
y_train = y[:train_size]
y_test = y[train_size:]
# 4.
print(X_train.shape)
print(y_tain.shape)

(140, 3)


NameError: name 'y_tain' is not defined

In [ ]:
# 5. 
m = X_train.shape[0]
n = X_train.shape[1]
# 6.
X_train_rand = X_train[np.random.randint(0,m)]
X_train_rand = X_train_rand.reshape(1,n)
print(X_train_rand)

In [ ]:
# 7.
rand = np.random.randint(0,m-50)
mini_batch_X = X_train[rand:rand+50]
print(mini_batch_X.shape)

In [ ]:
# 8.
batch_size = int(m / 10)
for i in range(0, m, batch_size):
    batch = X_train[i:i+batch_size]
    print(batch.shape)

In [ ]:
# 9.
theta = np.zeros(n)
print(theta.shape)

In [ ]:
# 10.
yhat = X_train @ theta
print(yhat.shape)

In [ ]:
# 11.
y = np.random.uniform(0,1,yhat.shape)
print(y.shape)

In [ ]:
# 12.
result = sum((y-yhat)**2)/m
print(result)

### === Task 4 ===

1. From the above <code>X_train</code> from previous task, using concatenation, add a column of 1s along axis=1 and call it intercept

2. Create a <code>theta</code> of shape (n + 1, 4), with random values between 0 and 1

3. Perform a dot product between X_train and theta, and assign this value to a variable called <code>hot_encoded_yhat</code>

4. Continuing, using broadcasting and vectorization, for each value (here I use example as value1) in <code>hot_encoded_yhat</code>, perform the following calculations.

$$ \frac{\exp(value1)}{\exp(value1)+\exp(value2)+\exp(value3)+\exp(value4)} $$

For example, if my first row is [0.3, 0.5, 1.2, 3.1], then the first value 0.3 will change to

exp(0.3) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

The second value 0.5 will become

exp(0.5) / (exp(0.3) + exp(0.5) + exp(1.2) + exp(3.1))

5. Create a variable called <code>yhat</code> which is equal to the <code>np.argmax</code> of <code>hot_encoded_yhat</code> along axis=1.  That is, <code>yhat</code> has the shape of <code>(X_train.shape[0], )</code>.  For example, if the first row of <code>hot_encoded_yhat</code> is [0.1, 0.2, 0.3, 0.4], since the fourth value is the biggest, the value will be its index which is 3.

6. Create a variable called <code>y</code>, containing shape of <code>(X_train.shape[0], )</code> but with random int values from [0, 1, 2, 3]

7. Assign a variable <code>n_classses</code> equal to the number of unique values in <code>y</code>

In [243]:
# 1.
intercept = np.ones((m, 1))
X_train = np.concatenate((intercept, X_train), axis=1)
print(X_train.shape)

(140, 5)


In [244]:
# 2.
theta = np.random.uniform(0,1,(n+1,4))
print(theta.shape)

(4, 4)


In [245]:
# 3.
hot_encoded_yhat = X_train @ theta
print(hot_encoded_yhat.shape)
print(hot_encoded_yhat[1])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [246]:
# 4.
hot_encoded_yhat = np.exp(hot_encoded_yhat)/np.sum(np.exp(hot_encoded_yhat), axis=1, keepdims=True)
print(hot_encoded_yhat.shape)
print(hot_encoded_yhat[0])

(140, 4)
[0.20576128 0.30180467 0.19253872 0.29989534]


In [247]:
# 5.
yhat = np.argmax(hot_encoded_yhat, axis=1)
print(yhat.shape)
print(yhat)

(140,)
[1 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [248]:
# 6.
y = np.random.randint(0,4,yhat.shape)
print(y.shape)
print(y)

(140,)
[1 1 3 3 2 2 1 2 0 0 3 2 3 2 0 3 2 2 0 2 2 0 2 2 2 0 2 2 0 1 0 2 1 3 1 1 2
 0 2 3 2 2 3 3 0 2 1 2 0 3 2 2 1 3 3 0 0 0 0 0 1 2 0 1 1 0 1 1 2 1 1 0 2 0
 1 3 2 3 3 3 3 2 3 2 3 0 1 1 2 2 0 2 3 1 0 1 1 0 3 2 1 3 0 2 3 0 2 3 1 3 0
 1 0 1 1 3 2 2 1 2 1 3 2 2 0 1 1 1 0 3 0 1 1 1 2 3 2 2 1 2]


In [249]:
# 7.
n_classses = np.unique(y)
print(n_classses)
print(len(n_classses))

[0 1 2 3]
4


### === Task 5 ===

1. Take the above variables <code>yhat</code> and <code>y</code>, sum up the counts when their corresponding value are the same.  Then divide this sum by $m$.  Called this variable <code>accuracy</code>

2. Let's practice masking.  Convert <code>y</code> into <code>hot_encoded_y</code> matrix of shape <code>(X_train.shape[0], 4)</code>, where the column will be one according to its value, and other columns will be zero.  For example, if the first row is 1, then it will become 0 1 0 0.  If the second row is 2, then it will become 0 0 1 0

3. Grab the data from <code>data = np.genfromtxt('../data/perceptron.csv', delimiter=',', skip_header=1)</code>
    - set X to be all columns except last
    - set y to be the last column
    - select X where its corresponding y is 0
    - select X where its corresponding y is 1
    
4. Grab the data from <code>iris = np.genfromtxt('../data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)</code>
    - set iris_without_headers to all rows except the first row
    - set sepal_length to second column of iris_without_headers
    - set petal_length to fourth column of iris_without_headers
    - print the shape of iris_without_headers where sepal_length is less than 5, and petal_length is greater than 1.5

In [250]:
# 1.
accuracy = ((yhat == y).sum())/m
print(accuracy)

0.21428571428571427


In [251]:
# 2.
k = 4
hot_encoded_y = np.zeros((m, k))
for i in range(len(y)):
    hot_encoded_y[i,y[i]] = 1
print(y[:5])
print(hot_encoded_y[:5])

[1 1 3 3 2]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [240]:
# 3.
data = np.genfromtxt('data/perceptron.csv', delimiter=',', skip_header=1)
X = data[:,:-1]
y = data[:,-1]
print(type(y))
print("X where y=0:")
print(X[y==0])
print("X where y=1:")
print(X[y==1])

<class 'numpy.ndarray'>
X where y=0:
[[0.4946 5.7661]
 [1.2888 5.3433]
 [1.4293 4.5592]
 [1.1921 5.8563]
 [1.063  5.7357]
 [1.5079 5.8622]
 [0.2678 6.9931]
 [0.9726 3.6268]
 [2.5389 3.3884]
 [2.473  5.6404]]
X where y=1:
[[4.7206 5.7661]
 [4.2898 5.3433]
 [4.2286 4.5592]
 [3.1454 5.8563]
 [5.1043 5.7357]
 [3.9799 5.8622]
 [4.5288 6.9931]
 [4.106  3.6268]
 [4.7555 3.3884]
 [4.7977 5.6404]]


In [254]:
# 4. 
iris = np.genfromtxt('data/iris.csv', delimiter=',', encoding="utf-8", dtype=None)
iris_without_headers = iris[1:,:]
sepal_length = iris_without_headers[:,1].astype(float)
petal_length = iris_without_headers[:,3].astype(float)

selected = iris_without_headers[np.logical_and(sepal_length<5, petal_length>1.5)]
# OR another way
cond1 = sepal_length<5 
cond2 = petal_length>1.5
selected = iris_without_headers[cond1 & cond2]

print(selected)
print(selected.shape)

[['12' '4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['25' '4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['30' '4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['31' '4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['107' '4.9' '2.5' '4.5' '1.7' 'Iris-virginica']]
(5, 6)
