### ===Task===

Load the iris data, and use this Gaussian Naive Classification.  Put them into class and calculate accuracy accordingly.

In [6]:
# Import library
from sklearn.datasets import make_classification, make_blobs
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Load the data
X, y = make_classification(n_samples=500, n_features=10, n_informative=4,
                             n_clusters_per_class=2, random_state=14)


#X, y = make_blobs(n_samples=500, centers=3, n_features=2, random_state=0)


# Scale
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print(X.shape)
print(y.shape)
print(np.unique(y))

(500, 10)
(500,)
[0 1]


In [43]:
class GaussianNaive:
    def __init__(self):
        pass

    def fit(self, X, y):
        n = X.shape[1]
        k =len(np.unique(y))
        self.mean = np.zeros((k, n))
        self.std = np.zeros((k, n))
        m = []
        for label in range(k):
            self.mean[label, :] = X[y==label].mean(axis=0)
            self.std[label, :]  = X[y==label].std(axis=0)
            m.append(len(X[y==label]))
        self.prior = m/sum(m)

    def gaussian_pdf(self, X, mean, std):
        left = 1 / (np.sqrt(2 * np.pi) * std)
        e = (X - mean) ** 2 / (2 * (std ** 2))
        right = np.exp(-e)
        return left*right

    def predict(self):
        pass


In [8]:
def gaussian_pdf( X, mean, std):
    left = 1 / (np.sqrt(2 * np.pi) * std)
    e = (X - mean) ** 2 / (2 * (std ** 2))
    right = np.exp(-e)
    return left*right

In [41]:
k=2
n = X.shape[1]
mean = np.zeros((k, n))
std = np.zeros((k, n))
m = np.zeros(k)
for label in range(k):
    mean[label, :] = X[y==label].mean(axis=0)
    std[label, :]  = X[y==label].std(axis=0)
    m[label] = (len(X[y==label]))
prior = m/sum(m)
px_y = []
total_likelihood = []
posterior = np.zeros((X_test.shape[0], k))
for label in range(k):
    px_y = gaussian_pdf(X_test, mean[label,:],std[label,:])
    total_likelihood = np.prod(px_y, axis=1)
    posterior[:,label] = prior[label]*total_likelihood

yhat = np.argmax(posterior, axis=1)
print(posterior.shape)
print(posterior[:4,0])
print(posterior[:4,1])
print(yhat[:4])
#posterior = prior*total_likelihood
#print(posterior)

(150, 2)
[2.77346913e-08 7.47571202e-07 1.39682460e-06 9.64159126e-08]
[5.57199485e-15 1.37026661e-08 1.46545308e-05 1.61325869e-10]
[0 0 1 0]
